import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useLocation } from 'react-router-dom';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function AdminDashboard() {
  const location = useLocation();
  const [activeTab, setActiveTab] = useState('overview');
  const [isExporting, setIsExporting] = useState(false);

  useEffect(() => {
    if (location.pathname.includes('/hospitals')) setActiveTab('hospitals');
    else if (location.pathname.includes('/donors')) setActiveTab('donors');
    else if (location.pathname.includes('/analytics')) setActiveTab('analytics');
    else if (location.pathname.includes('/settings')) setActiveTab('settings');
    else setActiveTab('overview');
  }, [location.pathname]);

  const handleExportPDF = () => {
    setIsExporting(true);
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();

    // Branded Header
    doc.setFillColor(238, 43, 43); // #ee2b2b
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('LifeLink AI', 20, 20);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Monthly Network Performance Report', 20, 30);
    doc.text(`Generated: ${timestamp}`, 140, 20);

    // Section 1: Summary Statistics
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Network Health Summary', 20, 55);

    autoTable(doc, {
      startY: 60,
      head: [['Metric', 'Current Value', 'Growth', 'Network Status']],
      body: [
        ['Total Active Donors', '12,402', '+12%', 'Healthy'],
        ['Hospital Partners', '156 Facilities', '+5%', 'Expanding'],
        ['Successful Life-Saves', '8,920', '+18%', 'Active'],
        ['Avg. Response Time', '12.4 Minutes', '-15%', 'Optimal'],
        ['AI Prediction Accuracy', '98.2%', '+0.4%', 'High Performance']
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42] },
      margin: { left: 20, right: 20 }
    });

    // Section 2: Regional Demand (from Analytics View data)
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Regional Demand Forecast (Next 7 Days)', 20, (doc as any).lastAutoTable.finalY + 20);

    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 25,
      head: [['Region', 'Hospital Load', 'Risk Level', 'Supply Buffer']],
      body: [
        ['North District', '75%', 'Moderate', '84 Hours'],
        ['South Harbor', '95%', 'CRITICAL', '12 Hours'],
        ['East Bay', '40%', 'Low', '120 Hours'],
        ['West Hill', '65%', 'Moderate', '62 Hours']
      ],
      headStyles: { fillColor: [238, 43, 43] },
      margin: { left: 20, right: 20 }
    });

    // Section 3: System Insights
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 116, 139); // slate-400
    doc.text('Note: This report is generated by LifeLink AI engine based on real-time network telemetry.', 20, finalY);
    doc.text('All donor data is cryptographically secured & HIPAA compliant.', 20, finalY + 7);

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount}`, 180, 285);
    }

    doc.save(`LifeLink-Network-Report-${new Date().toISOString().split('T')[0]}.pdf`);

    setTimeout(() => {
      setIsExporting(false);
    }, 1000);
  };

  return (
    <div className="p-8 space-y-8 max-w-7xl mx-auto w-full relative">
      {/* Title & Actions */}
      <div className="flex justify-between items-end">
        <div>
          <h2 className="text-2xl font-extrabold text-slate-900">
            {activeTab === 'overview' && "Network Health Overview"}
            {activeTab === 'hospitals' && "Hospital Network Management"}
            {activeTab === 'donors' && "Donor Database"}
            {activeTab === 'analytics' && "Regional Analytics & Planning"}
            {activeTab === 'settings' && "System Settings"}
          </h2>
          <p className="text-slate-500">
            {activeTab === 'overview' && "Real-time status of LifeLink AI donor-hospital connectivity."}
            {activeTab === 'hospitals' && "Monitor and manage registered medical facilities."}
            {activeTab === 'donors' && "Overview of active blood donors in the network."}
            {activeTab === 'analytics' && "Analysis of regional hospital demand vs. donor availability."}
            {activeTab === 'settings' && "Configure system-wide parameters and AI thresholds."}
          </p>
        </div>
        <div className="flex gap-3">
          <button className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-all">
            <span className="material-symbols-outlined text-sm">calendar_today</span>
            <span>Last 30 Days</span>
          </button>
          <button
            onClick={handleExportPDF}
            disabled={isExporting}
            className="flex items-center gap-2 px-6 py-3 bg-[#ee2b2b] text-white rounded-xl text-xs font-black uppercase tracking-widest hover:bg-[#ee2b2b]/90 shadow-xl shadow-[#ee2b2b]/20 transition-all active:scale-95 disabled:opacity-50"
          >
            <span className="material-symbols-outlined text-sm">{isExporting ? 'sync' : 'file_download'}</span>
            <span>{isExporting ? 'Generating Report...' : 'Export PDF Report'}</span>
          </button>
        </div>
      </div>

      {activeTab === 'overview' && <OverviewView />}
      {activeTab === 'hospitals' && <HospitalsView />}
      {activeTab === 'donors' && <DonorsView />}
      {activeTab === 'analytics' && <RegionalAnalyticsView />}
      {activeTab === 'settings' && <SettingsView />}
    </div>
  );
}

function SettingsView() {
  const [notifications, setNotifications] = useState({ email: true, sms: false, push: true, critical: true });
  const [aiSettings, setAiSettings] = useState({ autoMatch: true, predictiveDemand: true, anomalyDetection: false, learningMode: true });
  const [showToast, setShowToast] = useState(false);
  const [toastMsg, setToastMsg] = useState('');

  const showSuccess = (msg: string) => {
    setToastMsg(msg);
    setShowToast(true);
    setTimeout(() => setShowToast(false), 3000);
  };

  const Toggle = ({ value, onChange }: { value: boolean; onChange: () => void }) => (
    <button
      onClick={onChange}
      className={`relative w-12 h-6 rounded-full transition-all duration-300 ${value ? 'bg-[#ee2b2b]' : 'bg-slate-200'
        }`}
    >
      <span className={`absolute top-1 w-4 h-4 bg-white rounded-full shadow-md transition-all duration-300 ${value ? 'left-7' : 'left-1'
        }`} />
    </button>
  );

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-300 relative">

      {showToast && (
        <div className="fixed top-8 right-8 bg-slate-900 text-white px-6 py-3 rounded-xl shadow-2xl z-[100] flex items-center gap-3 animate-in slide-in-from-right duration-300">
          <span className="material-symbols-outlined text-emerald-400">check_circle</span>
          <span className="text-sm font-bold">{toastMsg}</span>
        </div>
      )}

      {/* Account Profile */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-8 py-6 border-b border-slate-100 flex items-center gap-3">
          <span className="material-symbols-outlined text-[#ee2b2b]">manage_accounts</span>
          <h3 className="text-lg font-black text-slate-900">Account Profile</h3>
        </div>
        <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Full Name</label>
            <input defaultValue="System Administrator" className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#ee2b2b]/20 focus:border-[#ee2b2b]/40 transition-all" />
          </div>
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Email Address</label>
            <input defaultValue="admin@lifelink.ai" className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#ee2b2b]/20 focus:border-[#ee2b2b]/40 transition-all" />
          </div>
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Phone Number</label>
            <input defaultValue="+1 (555) 000-0000" className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#ee2b2b]/20 focus:border-[#ee2b2b]/40 transition-all" />
          </div>
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Timezone</label>
            <select className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#ee2b2b]/20 transition-all">
              <option>UTC-8 (Pacific Time)</option>
              <option>UTC-5 (Eastern Time)</option>
              <option>UTC+0 (GMT)</option>
              <option>UTC+5:30 (IST)</option>
            </select>
          </div>
          <div className="md:col-span-2 flex justify-end">
            <button onClick={() => showSuccess('Profile updated successfully!')} className="px-8 py-3 bg-[#ee2b2b] text-white rounded-xl font-black text-xs uppercase tracking-wider hover:bg-[#ee2b2b]/90 shadow-lg shadow-[#ee2b2b]/20 transition-all active:scale-95">
              Save Profile
            </button>
          </div>
        </div>
      </div>

      {/* Notification Preferences */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-8 py-6 border-b border-slate-100 flex items-center gap-3">
          <span className="material-symbols-outlined text-blue-500">notifications</span>
          <h3 className="text-lg font-black text-slate-900">Notification Preferences</h3>
        </div>
        <div className="p-8 space-y-6">
          {[
            { key: 'email', label: 'Email Notifications', desc: 'Receive alerts and reports via email', icon: 'mail' },
            { key: 'sms', label: 'SMS Alerts', desc: 'Critical emergency alerts via text message', icon: 'sms' },
            { key: 'push', label: 'Push Notifications', desc: 'In-app dashboard push alerts', icon: 'notifications_active' },
            { key: 'critical', label: 'Critical Only Mode', desc: 'Only send alerts for supply deficits and emergencies', icon: 'emergency' },
          ].map(item => (
            <div key={item.key} className="flex items-center justify-between p-5 rounded-2xl bg-slate-50 border border-slate-100 hover:border-slate-200 transition-all">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-500 flex items-center justify-center">
                  <span className="material-symbols-outlined text-lg">{item.icon}</span>
                </div>
                <div>
                  <p className="font-black text-slate-800 text-sm">{item.label}</p>
                  <p className="text-xs text-slate-400 font-medium mt-0.5">{item.desc}</p>
                </div>
              </div>
              <Toggle value={(notifications as any)[item.key]} onChange={() => setNotifications(p => ({ ...p, [item.key]: !(p as any)[item.key] }))} />
            </div>
          ))}
          <div className="flex justify-end">
            <button onClick={() => showSuccess('Notification preferences saved!')} className="px-8 py-3 bg-slate-900 text-white rounded-xl font-black text-xs uppercase tracking-wider hover:bg-slate-700 transition-all active:scale-95">
              Save Preferences
            </button>
          </div>
        </div>
      </div>

      {/* AI Engine Configuration */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-8 py-6 border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="material-symbols-outlined text-[#ee2b2b]">auto_awesome</span>
            <h3 className="text-lg font-black text-slate-900">AI Engine Configuration</h3>
          </div>
          <div className="flex items-center gap-2 bg-emerald-50 border border-emerald-100 px-3 py-1.5 rounded-full">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            <span className="text-[10px] font-black text-emerald-700 uppercase">Engine Online</span>
          </div>
        </div>
        <div className="p-8 space-y-6">
          {[
            { key: 'autoMatch', label: 'Autonomous Donor Matching', desc: 'AI automatically pairs donors with hospital requests', icon: 'hub' },
            { key: 'predictiveDemand', label: 'Predictive Demand Forecasting', desc: 'Forecast regional blood demands 7 days ahead', icon: 'insights' },
            { key: 'anomalyDetection', label: 'Anomaly Detection', desc: 'Flag unusual network activity or supply chain gaps', icon: 'policy' },
            { key: 'learningMode', label: 'Continuous Learning Mode', desc: 'Allow AI to learn from match outcomes to improve accuracy', icon: 'model_training' },
          ].map(item => (
            <div key={item.key} className="flex items-center justify-between p-5 rounded-2xl bg-slate-50 border border-slate-100 hover:border-[#ee2b2b]/20 transition-all">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-xl bg-[#ee2b2b]/10 text-[#ee2b2b] flex items-center justify-center">
                  <span className="material-symbols-outlined text-lg">{item.icon}</span>
                </div>
                <div>
                  <p className="font-black text-slate-800 text-sm">{item.label}</p>
                  <p className="text-xs text-slate-400 font-medium mt-0.5">{item.desc}</p>
                </div>
              </div>
              <Toggle value={(aiSettings as any)[item.key]} onChange={() => setAiSettings(p => ({ ...p, [item.key]: !(p as any)[item.key] }))} />
            </div>
          ))}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-100">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">AI Confidence Threshold</label>
            <div className="flex items-center gap-4 mt-3">
              <input type="range" min="50" max="99" defaultValue="85" className="flex-1 accent-[#ee2b2b]" />
              <span className="text-sm font-black text-slate-800 w-12">85%</span>
            </div>
            <p className="text-[10px] text-slate-400 mt-2">Minimum confidence required before AI executes autonomous recommendations</p>
          </div>
          <div className="flex justify-end">
            <button onClick={() => showSuccess('AI Engine settings updated!')} className="px-8 py-3 bg-[#ee2b2b] text-white rounded-xl font-black text-xs uppercase tracking-wider hover:bg-[#ee2b2b]/90 shadow-lg shadow-[#ee2b2b]/20 transition-all active:scale-95">
              Apply AI Config
            </button>
          </div>
        </div>
      </div>

      {/* Security */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-8 py-6 border-b border-slate-100 flex items-center gap-3">
          <span className="material-symbols-outlined text-emerald-500">security</span>
          <h3 className="text-lg font-black text-slate-900">Security & Access Control</h3>
        </div>
        <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Current Password</label>
            <input type="password" placeholder="••••••••" className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-200 transition-all" />
          </div>
          <div className="space-y-2">
            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">New Password</label>
            <input type="password" placeholder="••••••••" className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-200 transition-all" />
          </div>
          <div className="md:col-span-2 flex items-center justify-between p-5 rounded-2xl bg-emerald-50 border border-emerald-100">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-600 flex items-center justify-center">
                <span className="material-symbols-outlined text-lg">verified_user</span>
              </div>
              <div>
                <p className="font-black text-slate-800 text-sm">Two-Factor Authentication (2FA)</p>
                <p className="text-xs text-slate-400 font-medium mt-0.5">Secure your admin account with an authenticator app</p>
              </div>
            </div>
            <button className="px-5 py-2.5 border border-emerald-200 text-emerald-700 font-black text-xs uppercase rounded-xl hover:bg-emerald-100 transition-all">Enable 2FA</button>
          </div>
          <div className="md:col-span-2 flex justify-end">
            <button onClick={() => showSuccess('Password updated successfully!')} className="px-8 py-3 bg-emerald-600 text-white rounded-xl font-black text-xs uppercase tracking-wider hover:bg-emerald-700 transition-all active:scale-95">
              Update Password
            </button>
          </div>
        </div>
      </div>

      {/* Danger Zone */}
      <div className="bg-white rounded-2xl border border-red-100 shadow-sm overflow-hidden">
        <div className="px-8 py-6 border-b border-red-100 flex items-center gap-3 bg-red-50/50">
          <span className="material-symbols-outlined text-[#ee2b2b]">warning</span>
          <h3 className="text-lg font-black text-[#ee2b2b]">Danger Zone</h3>
        </div>
        <div className="p-8 space-y-4">
          <div className="flex items-center justify-between p-5 rounded-2xl bg-slate-50 border border-slate-100">
            <div>
              <p className="font-black text-slate-800 text-sm">Purge AI Match Cache</p>
              <p className="text-xs text-slate-400 mt-0.5">Clear all cached predictions and reset the match queue</p>
            </div>
            <button onClick={() => showSuccess('AI cache purged successfully!')} className="px-5 py-2.5 border border-amber-200 bg-amber-50 text-amber-700 font-black text-xs uppercase rounded-xl hover:bg-amber-100 transition-all">Purge Cache</button>
          </div>
          <div className="flex items-center justify-between p-5 rounded-2xl bg-red-50/50 border border-red-100">
            <div>
              <p className="font-black text-red-700 text-sm">Reset Network Data</p>
              <p className="text-xs text-red-400 mt-0.5">This will permanently reset all network statistics. Cannot be undone.</p>
            </div>
            <button className="px-5 py-2.5 border border-red-200 bg-white text-[#ee2b2b] font-black text-xs uppercase rounded-xl hover:bg-red-50 transition-all">Reset All</button>
          </div>
        </div>
      </div>
    </div>
  );
}

function RegionalAnalyticsView() {
  return (
    <div className="space-y-8">
      {/* Analytics KPIs */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-xl border border-slate-200">
          <p className="text-slate-500 text-xs font-bold uppercase tracking-wider">Avg. Response Time</p>
          <h3 className="text-2xl font-black text-slate-900 mt-1">12.4 Min</h3>
          <p className="text-emerald-500 text-[10px] font-bold flex items-center gap-1 mt-2">
            <span className="material-symbols-outlined text-xs">trending_down</span>
            -15% from last week
          </p>
        </div>
        <div className="bg-white p-6 rounded-xl border border-slate-200">
          <p className="text-slate-500 text-xs font-bold uppercase tracking-wider">Cross-Region Efficiency</p>
          <h3 className="text-2xl font-black text-slate-900 mt-1">92.8%</h3>
          <div className="mt-3 w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
            <div className="bg-emerald-500 h-full rounded-full" style={{ width: '92.8%' }}></div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-xl border border-slate-200">
          <p className="text-slate-500 text-xs font-bold uppercase tracking-wider">AI Prediction Accuracy</p>
          <h3 className="text-2xl font-black text-slate-900 mt-1">98.2%</h3>
          <p className="text-slate-400 text-[10px] mt-2 italic">Based on 5k+ previous matches</p>
        </div>
        <div className="bg-white p-6 rounded-xl border border-[#ee2b2b]/30 bg-red-50/30">
          <p className="text-red-600 text-xs font-bold uppercase tracking-wider">Supply Deficit</p>
          <h3 className="text-2xl font-black text-red-600 mt-1">O- / B-</h3>
          <p className="text-red-500 text-[10px] font-bold flex items-center gap-1 mt-2 animate-pulse">
            <span className="material-symbols-outlined text-xs">warning</span>
            Critical in 4 sectors
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Donor Availability Analysis */}
        <div className="bg-white p-6 rounded-xl border border-slate-200">
          <div className="flex justify-between items-center mb-6">
            <h3 className="font-bold text-slate-900 flex items-center gap-2">
              <span className="material-symbols-outlined text-[#ee2b2b]">person_search</span>
              Donor Availability Index
            </h3>
            <div className="flex gap-2">
              <span className="w-3 h-3 rounded-full bg-blue-500"></span>
              <span className="text-[10px] font-bold text-slate-500 uppercase">Registered</span>
              <span className="w-3 h-3 rounded-full bg-emerald-500 ml-2"></span>
              <span className="text-[10px] font-bold text-slate-500 uppercase">Available Now</span>
            </div>
          </div>
          <div className="space-y-6">
            {['North District', 'South Harbor', 'East Bay', 'West Hill'].map((reg, i) => (
              <div key={i} className="space-y-2">
                <div className="flex justify-between items-center text-sm">
                  <span className="font-bold text-slate-700">{reg}</span>
                  <span className="text-slate-500 font-medium">840 / 1,200 available</span>
                </div>
                <div className="w-full bg-slate-100 h-3 rounded-lg overflow-hidden flex">
                  <div className="bg-blue-500 h-full border-r border-white/20" style={{ width: '85%' }}></div>
                  <div className="bg-emerald-500 h-full" style={{ width: `${Math.random() * 40 + 30}%` }}></div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Hospital Demand Forecast */}
        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 rounded-full -translate-y-1/2 translate-x-1/2 blur-2xl"></div>

          <div className="flex justify-between items-start mb-8">
            <div>
              <h3 className="font-black text-slate-900 flex items-center gap-2 text-lg">
                <span className="material-symbols-outlined text-blue-500">analytics</span>
                Weekly Hospital Demand Forecast
              </h3>
              <p className="text-xs text-slate-400 font-bold mt-1 uppercase tracking-widest">AI Projected Resource Needs</p>
            </div>
            <div className="flex items-center gap-1 bg-blue-50 px-3 py-1.5 rounded-full border border-blue-100">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse"></span>
              <span className="text-[10px] font-black text-blue-600 uppercase">Live Prediction</span>
            </div>
          </div>

          <div className="h-[220px] flex items-end justify-between gap-3 px-2 mb-4">
            {[
              { day: 'MON', val: 75, trend: 'up' },
              { day: 'TUE', val: 55, trend: 'steady' },
              { day: 'WED', val: 40, trend: 'down' },
              { day: 'THU', val: 65, trend: 'up' },
              { day: 'FRI', val: 95, trend: 'peak' },
              { day: 'SAT', val: 80, trend: 'steady' },
              { day: 'SUN', val: 60, trend: 'down' }
            ].map((item, i) => (
              <div key={i} className="flex-1 flex flex-col items-center gap-3 group/bar h-full justify-end">
                <div className="relative w-full h-full flex flex-col justify-end">
                  <motion.div
                    initial={{ height: 0 }}
                    animate={{ height: `${item.val}%` }}
                    transition={{ delay: i * 0.1, duration: 1, ease: "circOut" }}
                    className={`w-full rounded-t-xl transition-all relative ${item.trend === 'peak'
                      ? 'bg-gradient-to-t from-[#ee2b2b] to-red-400 shadow-lg shadow-red-200'
                      : 'bg-gradient-to-t from-slate-200 to-slate-100 group-hover/bar:from-blue-100 group-hover/bar:to-blue-50'
                      }`}
                  >
                    <div className="absolute -top-10 left-1/2 -translate-x-1/2 bg-slate-900 text-white text-[10px] font-black px-2 py-1 rounded opacity-0 group-hover/bar:opacity-100 transition-all pointer-events-none whitespace-nowrap z-10">
                      {item.val}% LOAD
                    </div>
                  </motion.div>
                </div>
                <span className={`text-[10px] font-black tracking-tighter ${item.trend === 'peak' ? 'text-[#ee2b2b]' : 'text-slate-400'}`}>
                  {item.day}
                </span>
              </div>
            ))}
          </div>

          <div className="mt-8 grid grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-slate-50 border border-slate-100 flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-600 flex items-center justify-center">
                <span className="material-symbols-outlined text-lg">schedule</span>
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Peak Demand Window</p>
                <p className="text-xs font-black text-slate-700 mt-0.5">Fri, 18:00 - 22:00</p>
              </div>
            </div>
            <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-100 flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-600 flex items-center justify-center">
                <span className="material-symbols-outlined text-lg">verified</span>
              </div>
              <div>
                <p className="text-[10px] font-black text-emerald-600 uppercase tracking-widest">Inventory Status</p>
                <p className="text-xs font-black text-emerald-700 mt-0.5">Optimal (84h Buffer)</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function OverviewView() {
  const [period, setPeriod] = useState<'monthly' | 'quarterly'>('monthly');

  const chartData = {
    monthly: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      donors: "M0,220 Q70,200 140,150 T280,120 T420,100 T560,70 T700,50 T800,30",
      matches: "M0,250 Q70,230 140,190 T280,160 T420,130 T560,90 T700,70 T800,40",
      livesSaved: "M0,280 Q70,260 140,220 T280,180 T420,160 T560,110 T700,90 T800,60",
      gradient: "M0,220 Q70,200 140,150 T280,120 T420,100 T560,70 T700,50 T800,30 L800,300 L0,300 Z",
    },
    quarterly: {
      labels: ["Q1 (1/4)", "Q2 (2/4)", "Q3 (3/4)", "Q4 (4/4)"],
      donors: "M0,180 Q200,160 400,100 T800,20",
      matches: "M0,210 Q200,190 400,140 T800,60",
      livesSaved: "M0,240 Q200,220 400,180 T800,100",
      gradient: "M0,180 Q200,160 400,100 T800,20 L800,300 L0,300 Z",
    }
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <KPICard title="Total Active Donors" value="12,402" icon="volunteer_activism" color="red" trend="+12%" progress={75} />
        <KPICard title="Hospital Network Size" value="156 Facilities" icon="domain" color="blue" trend="+5%" progress={45} />
        <KPICard title="Successful Matches" value="8,920" icon="bolt" color="amber" trend="+18%" progress={88} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 bg-white rounded-xl border border-slate-200 p-6 flex flex-col shadow-sm">
          <div className="flex justify-between items-center mb-8">
            <div>
              <h3 className="text-lg font-bold text-slate-900">Network Performance Trend</h3>
              <p className="text-sm text-slate-500">Regional impact and matching efficiency</p>
            </div>
            <div className="flex bg-slate-100 p-1 rounded-lg">
              <button
                onClick={() => setPeriod('monthly')}
                className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${period === 'monthly' ? 'bg-white shadow-sm text-slate-900' : 'text-slate-500 hover:text-slate-700'}`}
              >
                Monthly
              </button>
              <button
                onClick={() => setPeriod('quarterly')}
                className={`px-3 py-1 text-xs font-bold rounded-md transition-all ${period === 'quarterly' ? 'bg-white shadow-sm text-slate-900' : 'text-slate-500 hover:text-slate-700'}`}
              >
                Quarterly
              </button>
            </div>
          </div>
          <div className="flex-1 min-h-[300px] relative">
            <svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 800 300">
              <defs>
                <linearGradient id="chartGradientActive" x1="0" x2="0" y1="0" y2="1">
                  <stop offset="0%" stopColor="#ee2b2b" stopOpacity="0.1"></stop>
                  <stop offset="100%" stopColor="#ee2b2b" stopOpacity="0"></stop>
                </linearGradient>
              </defs>

              {/* Grid Lines */}
              {[0, 1, 2, 3].map((v) => (
                <line key={v} x1="0" y1={v * 100} x2="800" y2={v * 100} stroke="#f8fafc" strokeWidth="1" />
              ))}

              <motion.path
                initial={false}
                animate={{ d: chartData[period].gradient }}
                transition={{ duration: 0.8, ease: "anticipate" }}
                fill="url(#chartGradientActive)"
              ></motion.path>

              {/* Lives Saved Line - Green */}
              <motion.path
                initial={false}
                animate={{ d: chartData[period].livesSaved }}
                transition={{ duration: 0.8, ease: "anticipate" }}
                fill="none"
                stroke="#10b981"
                strokeLinecap="round"
                strokeWidth="3"
                strokeDasharray="4 4"
              ></motion.path>

              {/* Total Matches Line - Blue */}
              <motion.path
                initial={false}
                animate={{ d: chartData[period].matches }}
                transition={{ duration: 0.8, ease: "anticipate" }}
                fill="none"
                stroke="#3b82f6"
                strokeLinecap="round"
                strokeWidth="3"
              ></motion.path>

              {/* New Donors Line - Red */}
              <motion.path
                initial={false}
                animate={{ d: chartData[period].donors }}
                transition={{ duration: 0.8, ease: "anticipate" }}
                fill="none"
                stroke="#ee2b2b"
                strokeLinecap="round"
                strokeWidth="5"
              ></motion.path>

              {/* Dynamic Labels */}
              <div className="absolute -bottom-8 left-0 right-0 flex justify-between px-2">
                {chartData[period].labels.map((label, i) => (
                  <motion.span
                    key={label}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className="text-[9px] font-black text-slate-400 uppercase tracking-tighter"
                  >
                    {label}
                  </motion.span>
                ))}
              </div>
            </svg>
          </div>

          <div className="mt-12 pt-6 border-t border-slate-100 flex items-center justify-between">
            <div className="flex flex-wrap gap-8">
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-[#ee2b2b]"></span>
                <span className="text-[10px] font-black text-slate-600 uppercase">New Donors</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-[#3b82f6]"></span>
                <span className="text-[10px] font-black text-slate-600 uppercase">Total Matches</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-[#10b981]"></span>
                <span className="text-[10px] font-black text-slate-600 uppercase">Lives Saved</span>
              </div>
            </div>
            <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
              Live Network Pulse
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-6 flex flex-col shadow-sm max-h-[500px]">
          <h3 className="text-lg font-bold text-slate-900 mb-6">System Feedback</h3>
          <div className="flex-1 overflow-y-auto space-y-4 pr-2">
            <FeedbackItem name="City General Hospital" initial="CG" rating={4} text="AI prediction accuracy improved our match time by 40%. The emergency routing is seamless." role="HOSPITAL ADMIN" time="2M AGO" />
            <FeedbackItem name="John D. (Donor)" initial="JD" rating={5} text="The donor app is very intuitive. Glad to see where my blood is making a difference." role="PLATINUM DONOR" time="15M AGO" color="red" />
            <FeedbackItem name="St. Mary's Clinic" initial="SM" rating={5} text="Regional visibility of rare blood groups is a life-saver for our trauma unit." role="SURGICAL HEAD" time="48M AGO" color="blue" />
            <FeedbackItem name="Alice W. (Donor)" initial="AW" rating={5} text="Love the token reward system! It's great to be recognized for contributing." role="GOLD DONOR" time="1H AGO" color="amber" />
          </div>
        </div>
      </div>
    </div>
  );
}

function HospitalsView() {
  const [selectedHospital, setSelectedHospital] = useState<any>(null);

  const hospitals = [
    {
      id: 1,
      name: "City General Hospital",
      location: "Downtown Medical Zone, Sector 4",
      status: "Active",
      stock: "High",
      requests: 12,
      image: "https://images.unsplash.com/photo-1587350859728-117699f4a13d?auto=format&fit=crop&q=80&w=800",
      contact: "Dr. Adrian Thorne",
      efficiency: "94%",
      donors: 840
    },
    {
      id: 2,
      name: "St. Mary's Medical",
      location: "East Riverside, Suburbs",
      status: "Active",
      stock: "Low",
      requests: 8,
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800",
      contact: "Sarah Miller (Admin)",
      efficiency: "88%",
      donors: 420
    },
    {
      id: 3,
      name: "Westside Emergency",
      location: "Industrial Corridor, West Bay",
      status: "Maintenance",
      stock: "Medium",
      requests: 0,
      image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800",
      contact: "Tech Support (N/A)",
      efficiency: "N/A",
      donors: 0
    },
    {
      id: 4,
      name: "Children's Health",
      location: "Academic Heights, North Hills",
      status: "Active",
      stock: "Critical",
      requests: 24,
      image: "https://images.unsplash.com/photo-1538108197017-c1a938fc938d?auto=format&fit=crop&q=80&w=800",
      contact: "Dr. Elena Vance",
      efficiency: "97%",
      donors: 1205
    }
  ];

  if (selectedHospital) {
    return <HospitalDetailView hospital={selectedHospital} onBack={() => setSelectedHospital(null)} />;
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h3 className="text-xl font-bold text-slate-800">Global Facility Management</h3>
        <div className="flex gap-2">
          <div className="relative">
            <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm">search</span>
            <input type="text" placeholder="Search facilities..." className="pl-9 pr-4 py-2 bg-white border border-slate-200 rounded-lg text-xs w-64 focus:ring-2 focus:ring-[#ee2b2b]/20 transition-all outline-none" />
          </div>
          <button className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-bold hover:bg-slate-800 transition-colors">+ Add New Hospital</button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {hospitals.map((h) => (
          <motion.div
            key={h.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            whileHover={{ y: -4 }}
            onClick={() => setSelectedHospital(h)}
            className="group bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm hover:shadow-xl hover:border-[#ee2b2b]/20 transition-all cursor-pointer flex flex-col sm:flex-row"
          >
            <div className="w-full sm:w-48 h-48 sm:h-auto overflow-hidden relative">
              <img src={h.image} alt={h.name} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
              <div className="absolute top-3 left-3">
                <span className={`px-2 py-1 rounded-md text-[10px] font-black uppercase shadow-sm ${h.status === 'Active' ? 'bg-emerald-500 text-white' : 'bg-slate-500 text-white'
                  }`}>
                  {h.status}
                </span>
              </div>
            </div>
            <div className="p-5 flex-1 flex flex-col justify-between">
              <div>
                <div className="flex justify-between items-start">
                  <h4 className="font-extrabold text-slate-900 text-lg group-hover:text-[#ee2b2b] transition-colors">{h.name}</h4>
                  <span className={`text-[10px] font-black px-2 py-0.5 rounded border ${h.stock === 'Critical' ? 'border-[#ee2b2b] text-[#ee2b2b] bg-red-50' :
                    h.stock === 'Low' ? 'border-orange-500 text-orange-500 bg-orange-50' :
                      'border-slate-200 text-slate-500 bg-slate-50'
                    }`}>
                    {h.stock} STOCK
                  </span>
                </div>
                <div className="mt-2 flex items-center gap-1 text-slate-500">
                  <span className="material-symbols-outlined text-sm">location_on</span>
                  <span className="text-xs font-semibold truncate max-w-[200px]">{h.location}</span>
                </div>
              </div>

              <div className="mt-4 pt-4 border-t border-slate-50 grid grid-cols-3 gap-2">
                <div className="text-center">
                  <p className="text-[10px] font-bold text-slate-400">REQUESTS</p>
                  <p className="text-sm font-black text-slate-900">{h.requests}</p>
                </div>
                <div className="text-center">
                  <p className="text-[10px] font-bold text-slate-400">DONORS</p>
                  <p className="text-sm font-black text-slate-900">{h.donors}</p>
                </div>
                <div className="text-center">
                  <p className="text-[10px] font-bold text-slate-400">EFFICIENCY</p>
                  <p className="text-sm font-black text-emerald-600">{h.efficiency}</p>
                </div>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function HospitalDetailView({ hospital, onBack }: { hospital: any, onBack: () => void }) {
  const [activeModal, setActiveModal] = useState<'contact' | 'status' | 'ai' | null>(null);
  const [currentStatus, setCurrentStatus] = useState(hospital.status);
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [showToast, setShowToast] = useState(false);

  const handleUpdateStatus = (newStatus: string) => {
    setCurrentStatus(newStatus);
    setActiveModal(null);
    setShowToast(true);
    setTimeout(() => setShowToast(false), 3000);
  };

  const runAIOptimization = () => {
    setIsOptimizing(true);
    setTimeout(() => {
      setIsOptimizing(false);
      setActiveModal('ai');
    }, 2000);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-300 relative">
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-slate-500 hover:text-slate-900 font-bold transition-colors"
      >
        <span className="material-symbols-outlined">arrow_back</span>
        Back to List
      </button>

      {/* Toast Notification */}
      {showToast && (
        <div className="fixed top-8 right-8 bg-slate-900 text-white px-6 py-3 rounded-xl shadow-2xl z-[100] flex items-center gap-3 animate-in slide-in-from-right duration-300">
          <span className="material-symbols-outlined text-emerald-400">check_circle</span>
          <span className="text-sm font-bold">System status updated successfully!</span>
        </div>
      )}

      <div className="bg-white rounded-3xl border border-slate-200 overflow-hidden shadow-sm">
        <div className="relative h-64">
          <img src={hospital.image} alt={hospital.name} className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent flex items-end p-8">
            <div className="flex-1 text-white">
              <div className="flex items-center gap-3 mb-2">
                <span className="px-3 py-1 bg-[#ee2b2b] text-white text-[10px] font-black rounded-lg uppercase tracking-widest">Premium Facility</span>
                <span className={`px-3 py-1 backdrop-blur-md text-[10px] font-bold rounded-lg uppercase ${currentStatus === 'Active' ? 'bg-emerald-500/80' :
                  currentStatus === 'Maintenance' ? 'bg-amber-500/80' : 'bg-slate-500/80'
                  }`}>
                  {currentStatus}
                </span>
              </div>
              <h2 className="text-3xl font-black">{hospital.name}</h2>
              <div className="flex items-center gap-2 text-white/80 mt-2">
                <span className="material-symbols-outlined text-sm">location_on</span>
                <span className="text-sm font-medium">{hospital.location}</span>
              </div>
            </div>
            <div className="flex gap-4">
              <button
                onClick={() => setActiveModal('contact')}
                className="px-6 py-3 bg-white text-slate-900 rounded-xl font-bold text-sm hover:bg-slate-100 transition-all shadow-lg active:scale-95 flex items-center gap-2"
              >
                <span className="material-symbols-outlined text-lg">chat</span>
                Contact Admin
              </button>
              <button
                onClick={() => setActiveModal('status')}
                className="px-6 py-3 bg-[#ee2b2b] text-white rounded-xl font-bold text-sm hover:bg-[#ee2b2b]/90 transition-all shadow-lg shadow-[#ee2b2b]/20 active:scale-95 flex items-center gap-2"
              >
                <span className="material-symbols-outlined text-lg">sync</span>
                Update Status
              </button>
            </div>
          </div>
        </div>

        <div className="p-8 grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="col-span-2 space-y-8">
            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-6 flex items-center gap-2">
                <span className="material-symbols-outlined text-[#ee2b2b]">inventory_2</span>
                Blood Stock Levels
              </h3>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                {['O+', 'O-', 'A+', 'B+'].map((type, i) => (
                  <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-100 group hover:border-[#ee2b2b]/30 transition-all">
                    <p className="text-sm font-black text-slate-400 mb-1">{type}</p>
                    <p className="text-xl font-black text-slate-900">{Math.floor(Math.random() * 50 + 10)} Units</p>
                    <div className="mt-3 w-full bg-slate-200 h-1.5 rounded-full overflow-hidden">
                      <div className={`h-full rounded-full ${i === 1 ? 'bg-[#ee2b2b]' : 'bg-emerald-500'}`} style={{ width: `${Math.random() * 60 + 20}%` }}></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                <h4 className="font-bold text-slate-900 mb-4 flex items-center gap-2">
                  <span className="material-symbols-outlined text-blue-500">trending_up</span>
                  Usage Activity
                </h4>
                <div className="h-32 flex items-end gap-1">
                  {[40, 70, 45, 90, 65, 80, 50].map((v, i) => (
                    <div key={i} className="flex-1 bg-blue-500/20 rounded-t-sm relative group">
                      <div className="absolute bottom-0 w-full bg-blue-500 rounded-t-sm transition-all" style={{ height: `${v}%` }}></div>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-slate-500 mt-4 text-center">Last 7 Days Consumption</p>
              </div>

              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
                <h4 className="font-bold text-slate-900 mb-4 flex items-center gap-2">
                  <span className="material-symbols-outlined text-amber-500">history_edu</span>
                  Recent Encounters
                </h4>
                <div className="space-y-3">
                  {[1, 2, 3].map((item) => (
                    <div key={item} className="flex items-center justify-between text-xs">
                      <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-emerald-500"></div>
                        <span className="font-bold text-slate-700">O+ Match Fulfilled</span>
                      </div>
                      <span className="text-slate-400">2h ago</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="p-6 bg-slate-900 rounded-3xl text-white shadow-xl relative overflow-hidden group">
              {isOptimizing && (
                <div className="absolute inset-0 bg-slate-900/90 z-10 flex flex-col items-center justify-center">
                  <div className="w-12 h-12 border-4 border-white/20 border-t-white rounded-full animate-spin mb-4"></div>
                  <p className="text-xs font-bold animate-pulse uppercase tracking-widest">AI Scanning Patterns...</p>
                </div>
              )}
              <h3 className="text-xl font-bold mb-4">Facility Health</h3>
              <div className="space-y-6">
                <div>
                  <div className="flex justify-between text-xs font-bold text-slate-400 uppercase tracking-widest mb-2">
                    <span>Performance</span>
                    <span>94/100</span>
                  </div>
                  <div className="w-full bg-white/10 h-2 rounded-full overflow-hidden">
                    <div className="bg-[#ee2b2b] h-full rounded-full" style={{ width: '94%' }}></div>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-[10px] font-bold text-slate-400 uppercase">Avg Response</p>
                    <p className="text-lg font-black mt-1">8.2m</p>
                  </div>
                  <div>
                    <p className="text-[10px] font-bold text-slate-400 uppercase">Fulfillment</p>
                    <p className="text-lg font-black mt-1">98.5%</p>
                  </div>
                </div>
              </div>
              <button
                onClick={runAIOptimization}
                className="w-full mt-8 py-4 bg-white/10 hover:bg-[#ee2b2b] border border-white/20 rounded-2xl font-bold transition-all flex items-center justify-center gap-2 active:scale-95 group-hover:border-[#ee2b2b]"
              >
                <span className="material-symbols-outlined text-sm">auto_awesome</span>
                AI Optimization Report
              </button>
            </div>

            <div className="p-6 bg-white border border-slate-200 rounded-3xl">
              <h4 className="font-bold text-slate-900 mb-4">Admin Contact</h4>
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center text-[#ee2b2b]">
                  <span className="material-symbols-outlined text-2xl font-black">person</span>
                </div>
                <div>
                  <p className="font-bold text-slate-900">{hospital.contact}</p>
                  <p className="text-xs text-slate-500">Chief Medical Officer</p>
                </div>
              </div>
              <div className="mt-4 space-y-2">
                <div className="flex items-center gap-2 text-xs text-slate-600">
                  <span className="material-symbols-outlined text-sm">mail</span>
                  thorne.a@hospital.com
                </div>
                <div className="flex items-center gap-2 text-xs text-slate-600">
                  <span className="material-symbols-outlined text-sm">phone</span>
                  +1 (555) 902-1234
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* --- MODALS --- */}

      {/* Contact Admin Modal */}
      {activeModal === 'contact' && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[110] flex items-center justify-center p-6 animate-in fade-in duration-300">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white w-full max-w-lg rounded-3xl overflow-hidden shadow-2xl"
          >
            <div className="p-6 bg-[#ee2b2b] text-white flex justify-between items-center">
              <div className="flex items-center gap-3">
                <span className="material-symbols-outlined">forum</span>
                <h4 className="font-black text-lg">Message to {hospital.name}</h4>
              </div>
              <button onClick={() => setActiveModal(null)} className="hover:bg-white/20 p-1 rounded-full"><span className="material-symbols-outlined">close</span></button>
            </div>
            <div className="p-8 space-y-6">
              <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100 text-sm text-slate-600 italic">
                "Hello {hospital.contact}, this is the System Admin. We've noticed a low stock on O-Negative. Please confirm if you need an emergency dispatch."
              </div>
              <textarea
                className="w-full h-32 p-4 bg-slate-100 rounded-2xl border-none text-sm focus:ring-2 focus:ring-[#ee2b2b]/20 outline-none resize-none"
                placeholder="Type your priority message here..."
              ></textarea>
              <div className="flex gap-3">
                <button
                  onClick={() => { setActiveModal(null); setShowToast(true); setTimeout(() => setShowToast(false), 3000); }}
                  className="flex-1 py-4 bg-[#ee2b2b] text-white rounded-2xl font-extrabold text-sm hover:bg-[#ee2b2b]/90 transition-all flex items-center justify-center gap-2 shadow-lg shadow-[#ee2b2b]/20"
                >
                  <span className="material-symbols-outlined text-sm">send</span>
                  Send Priority Message
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      )}

      {/* Update Status Modal */}
      {activeModal === 'status' && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[110] flex items-center justify-center p-6 animate-in fade-in duration-300">
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="bg-white w-full max-w-sm rounded-[2rem] overflow-hidden shadow-2xl p-8"
          >
            <h4 className="text-xl font-black text-slate-900 mb-2">Network Status Control</h4>
            <p className="text-sm text-slate-500 mb-8">Override the automated network availability for this facility.</p>
            <div className="space-y-3">
              {[
                { id: 'Active', icon: 'check_circle', color: 'text-emerald-500', bg: 'bg-emerald-50' },
                { id: 'Maintenance', icon: 'settings', color: 'text-amber-500', bg: 'bg-amber-50' },
                { id: 'Inactive', icon: 'cancel', color: 'text-slate-500', bg: 'bg-slate-50' },
                { id: 'Emergency Only', icon: 'emergency', color: 'text-[#ee2b2b]', bg: 'bg-red-50' }
              ].map(opt => (
                <button
                  key={opt.id}
                  onClick={() => handleUpdateStatus(opt.id)}
                  className={`w-full flex items-center gap-4 p-4 rounded-2xl border border-transparent hover:border-slate-200 transition-all text-left group ${currentStatus === opt.id ? opt.bg + ' !border-slate-300' : ''}`}
                >
                  <span className={`material-symbols-outlined ${opt.color} group-hover:scale-110 transition-transform`}>{opt.icon}</span>
                  <span className={`font-bold text-sm ${currentStatus === opt.id ? 'text-slate-900' : 'text-slate-600'}`}>{opt.id}</span>
                  {currentStatus === opt.id && <span className="ml-auto material-symbols-outlined text-sm text-slate-400">check</span>}
                </button>
              ))}
            </div>
            <button onClick={() => setActiveModal(null)} className="w-full mt-6 py-3 text-slate-400 font-bold text-sm hover:text-slate-600">Cancel</button>
          </motion.div>
        </div>
      )}

      {/* AI Optimization Modal */}
      {activeModal === 'ai' && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[110] flex items-center justify-center p-6 animate-in fade-in duration-300">
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-[#0f172a] text-white w-full max-w-2xl rounded-[2.5rem] overflow-hidden shadow-2xl"
          >
            <div className="p-8 border-b border-white/10 flex justify-between items-center bg-gradient-to-r from-slate-900 to-[#0f172a]">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-[#ee2b2b]/20 rounded-2xl flex items-center justify-center text-[#ee2b2b]">
                  <span className="material-symbols-outlined text-3xl font-black">auto_awesome</span>
                </div>
                <div>
                  <h4 className="text-xl font-black">LifeLink AI Insights</h4>
                  <p className="text-xs text-white/50 font-bold uppercase tracking-widest">Facility Optimization Path</p>
                </div>
              </div>
              <button
                onClick={() => setActiveModal(null)}
                className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-all border border-white/10"
              >
                <span className="material-symbols-outlined text-sm">close</span>
              </button>
            </div>
            <div className="p-10 space-y-8">
              <div className="grid grid-cols-2 gap-6">
                <div className="space-y-4">
                  <p className="text-xs font-bold text-[#ee2b2b] uppercase tracking-tighter">Recommendation 1</p>
                  <h5 className="font-bold text-lg leading-snug">Redirect O+ Surplus from Sector 2</h5>
                  <p className="text-sm text-white/60 leading-relaxed">AI analysis suggests a 40% stock overflow in sibling facility 'Westside'. Moving 20 units will stabilize this facility's deficit.</p>
                </div>
                <div className="space-y-4">
                  <p className="text-xs font-bold text-emerald-500 uppercase tracking-tighter">Impact Projection</p>
                  <div className="p-6 rounded-2xl bg-white/5 border border-white/5 text-center">
                    <p className="text-3xl font-black text-emerald-500">+18%</p>
                    <p className="text-[10px] font-bold text-white/40 mt-1 uppercase">Monthly Efficiency Increase</p>
                  </div>
                </div>
              </div>

              <div className="p-6 rounded-3xl bg-[#ee2b2b]/10 border border-[#ee2b2b]/20 flex items-start gap-4">
                <span className="material-symbols-outlined text-[#ee2b2b] mt-1">emergency</span>
                <div>
                  <p className="font-extrabold text-sm text-[#ee2b2b] mb-1">Critical Insight Identified</p>
                  <p className="text-xs text-white/80 leading-relaxed font-medium">Predicted demand spike for AB Negative on Friday night due to regional event patterns. Recommend doubling reserve thresholds by Thursday morning.</p>
                </div>
              </div>

              <button
                onClick={() => { setActiveModal(null); setShowToast(true); }}
                className="w-full py-5 bg-[#ee2b2b] hover:bg-[#ee2b2b]/90 text-white rounded-2xl font-black transition-all flex items-center justify-center gap-3 shadow-xl shadow-[#ee2b2b]/20"
              >
                <span className="material-symbols-outlined">bolt</span>
                Deploy AI Recommendations Now
              </button>
            </div>
          </motion.div>
        </div>
      )}

    </div>
  );
}

function DonorsView() {
  const [selectedDonor, setSelectedDonor] = useState<any>(null);

  const donors = [
    {
      id: 1,
      name: "Sarah Jenkins",
      group: "O-",
      status: "Eligible",
      last: "2 weeks ago",
      location: "Seattle, WA",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400",
      totalDonations: 12,
      rank: "Diamond",
      history: [
        { date: "Feb 10, 2024", quantity: "450ml", tokens: 250, location: "City General" },
        { date: "Nov 15, 2023", quantity: "450ml", tokens: 250, location: "Red Cross #4" },
        { date: "Aug 22, 2023", quantity: "500ml", tokens: 300, location: "City General" },
        { date: "May 05, 2023", quantity: "450ml", tokens: 250, location: "Regional Hub" }
      ]
    },
    {
      id: 2,
      name: "Michael Chen",
      group: "A+",
      status: "Deferred",
      last: "3 days ago",
      location: "Bellevue, WA",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
      totalDonations: 8,
      rank: "Gold",
      history: [
        { date: "Jan 20, 2024", quantity: "450ml", tokens: 200, location: "Eastside Med" },
        { date: "Oct 12, 2023", quantity: "450ml", tokens: 200, location: "Eastside Med" },
        { date: "Jul 08, 2023", quantity: "450ml", tokens: 200, location: "St. Mary's" }
      ]
    },
    {
      id: 3,
      name: "Elena Rodriguez",
      group: "B-",
      status: "Eligible",
      last: "Today",
      location: "Redmond, WA",
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
      totalDonations: 15,
      rank: "Platinum",
      history: [
        { date: "Feb 23, 2024", quantity: "500ml", tokens: 350, location: "Regional Hub" },
        { date: "Dec 01, 2023", quantity: "450ml", tokens: 250, location: "Regional Hub" },
        { date: "Sep 14, 2023", quantity: "450ml", tokens: 250, location: "City General" },
        { date: "Jun 20, 2023", quantity: "450ml", tokens: 250, location: "City General" }
      ]
    },
    {
      id: 4,
      name: "David Kim",
      group: "AB+",
      status: "Eligible",
      last: "1 month ago",
      location: "Seattle, WA",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
      totalDonations: 6,
      rank: "Silver",
      history: [
        { date: "Jan 05, 2024", quantity: "450ml", tokens: 150, location: "St. Mary's" },
        { date: "Oct 22, 2023", quantity: "450ml", tokens: 150, location: "City General" },
        { date: "Jul 15, 2023", quantity: "450ml", tokens: 150, location: "St. Mary's" }
      ]
    }
  ];

  if (selectedDonor) {
    return <DonorProfileView donor={selectedDonor} onBack={() => setSelectedDonor(null)} />;
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h3 className="text-xl font-bold text-slate-800">Top Network Donors</h3>
        <div className="relative">
          <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm">search</span>
          <input type="text" placeholder="Search donors by name or blood group..." className="pl-9 pr-4 py-2 bg-white border border-slate-200 rounded-lg text-xs w-72 focus:ring-2 focus:ring-[#ee2b2b]/20 transition-all outline-none" />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {donors.map((d) => (
          <motion.div
            key={d.id}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            whileHover={{ y: -5 }}
            className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm hover:shadow-xl transition-all group"
          >
            <div className="h-32 bg-gradient-to-r from-[#ee2b2b] to-red-800 relative">
              <div className="absolute -bottom-10 left-1/2 -translate-x-1/2">
                <div className="w-20 h-20 rounded-full border-4 border-white overflow-hidden shadow-lg bg-white">
                  <img src={d.image} alt={d.name} className="w-full h-full object-cover" />
                </div>
              </div>
              <div className="absolute top-3 right-3">
                <span className="px-2 py-1 bg-white/20 backdrop-blur-md text-white text-[10px] font-black rounded uppercase">
                  {d.rank}
                </span>
              </div>
            </div>
            <div className="pt-12 p-6 text-center">
              <h4 className="font-extrabold text-slate-900 group-hover:text-[#ee2b2b] transition-colors">{d.name}</h4>
              <div className="flex items-center justify-center gap-2 mt-1">
                <span className="text-[10px] font-black bg-red-50 text-[#ee2b2b] px-2 py-0.5 rounded border border-[#ee2b2b]/20">TYPE {d.group}</span>
                <span className={`text-[10px] font-black px-2 py-0.5 rounded border ${d.status === 'Eligible' ? 'bg-green-50 text-green-600 border-green-200' : 'bg-red-50 text-red-600 border-red-200'
                  }`}>
                  {d.status.toUpperCase()}
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-4 flex items-center justify-center gap-1 font-medium">
                <span className="material-symbols-outlined text-sm">location_on</span>
                {d.location}
              </p>

              <div className="mt-6 pt-6 border-t border-slate-50 grid grid-cols-2 gap-2">
                <div>
                  <p className="text-[10px] font-bold text-slate-400 uppercase">Donations</p>
                  <p className="font-black text-slate-900">{d.totalDonations}</p>
                </div>
                <div>
                  <p className="text-[10px] font-bold text-slate-400 uppercase">Last Trip</p>
                  <p className="font-black text-slate-900 text-[11px] truncate">{d.last}</p>
                </div>
              </div>

              <button
                onClick={() => setSelectedDonor(d)}
                className="w-full mt-6 py-3 bg-slate-50 text-slate-600 font-black text-xs rounded-xl hover:bg-[#ee2b2b] hover:text-white transition-all active:scale-95"
              >
                View Profile
              </button>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function DonorProfileView({ donor, onBack }: { donor: any, onBack: () => void }) {
  const [isVerifying, setIsVerifying] = useState(false);
  const [verificationStatus, setVerificationStatus] = useState<'pending' | 'verified'>('pending');
  const [showToast, setShowToast] = useState(false);

  const handleVerify = () => {
    setIsVerifying(false);
    setVerificationStatus('verified');
    setShowToast(true);
    setTimeout(() => setShowToast(false), 3000);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-300 relative">
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-slate-500 hover:text-slate-900 font-bold transition-colors"
      >
        <span className="material-symbols-outlined">arrow_back</span>
        Back to Directory
      </button>

      {/* Toast Notification */}
      {showToast && (
        <div className="fixed top-8 right-8 bg-slate-900 text-white px-6 py-3 rounded-xl shadow-2xl z-[150] flex items-center gap-3 animate-in slide-in-from-right duration-300">
          <span className="material-symbols-outlined text-emerald-400">verified_user</span>
          <span className="text-sm font-bold">Donor documents verified & encrypted!</span>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Side: Profile Card */}
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-white rounded-3xl border border-slate-200 overflow-hidden shadow-sm p-8 text-center relative">
            {verificationStatus === 'verified' && (
              <div className="absolute top-6 right-6 text-emerald-500 bg-emerald-50 p-2 rounded-full border border-emerald-100 flex items-center justify-center animate-in zoom-in duration-500">
                <span className="material-symbols-outlined font-black">verified</span>
              </div>
            )}
            <div className="w-32 h-32 rounded-full border-4 border-slate-50 mx-auto overflow-hidden shadow-xl mb-6 relative">
              <img src={donor.image} alt={donor.name} className="w-full h-full object-cover" />
            </div>
            <h2 className="text-2xl font-black text-slate-900">{donor.name}</h2>
            <p className="text-sm font-bold text-[#ee2b2b] mt-1">{donor.rank} Member</p>

            <div className="grid grid-cols-2 gap-4 mt-8">
              <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Blood Type</p>
                <p className="text-2xl font-black text-[#ee2b2b]">{donor.group}</p>
              </div>
              <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                <p className="text-[10px] font-bold text-slate-400 uppercase mb-1">Total Impact</p>
                <p className="text-2xl font-black text-slate-900">{donor.totalDonations}</p>
              </div>
            </div>

            <div className="mt-8 space-y-3 text-left">
              <div className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl text-sm">
                <span className="font-bold text-slate-500 uppercase text-[10px]">Eligibility Status</span>
                <span className="font-black text-green-600">{donor.status}</span>
              </div>
              <div className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl text-sm">
                <span className="font-bold text-slate-500 uppercase text-[10px]">Network Points</span>
                <span className="font-black text-amber-600">4,250 PTS</span>
              </div>
            </div>
          </div>

          <div className={`p-8 rounded-3xl text-white shadow-xl transition-all duration-500 ${verificationStatus === 'verified' ? 'bg-emerald-900' : 'bg-slate-900'
            }`}>
            <h4 className="font-bold mb-4 flex items-center gap-2">
              <span className={`material-symbols-outlined ${verificationStatus === 'verified' ? 'text-emerald-400' : 'text-[#ee2b2b]'}`}>
                {verificationStatus === 'verified' ? 'verified_user' : 'verified'}
              </span>
              {verificationStatus === 'verified' ? 'Identity Secured' : 'Admin Verification'}
            </h4>
            <div className="space-y-4">
              <p className="text-xs text-white/60 leading-relaxed font-medium">
                {verificationStatus === 'verified'
                  ? 'All documentation has been officially reviewed and cryptographically secured in the network.'
                  : 'Verify donor identification and medical records history before next scheduled donation session.'}
              </p>
              {verificationStatus === 'pending' ? (
                <button
                  onClick={() => setIsVerifying(true)}
                  className="w-full py-4 bg-white/10 hover:bg-white/20 border border-white/20 rounded-2xl font-bold transition-all text-sm active:scale-95 flex items-center justify-center gap-2"
                >
                  <span className="material-symbols-outlined text-sm">assignment_ind</span>
                  Verify Documentation
                </button>
              ) : (
                <div className="w-full py-4 bg-emerald-500/20 rounded-2xl font-bold text-sm text-center border border-emerald-500/30 flex items-center justify-center gap-2">
                  <span className="material-symbols-outlined text-sm">check_circle</span>
                  Verified & Approved
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right Side: Donation History */}
        <div className="lg:col-span-2 space-y-8">
          <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-8 border-b border-slate-100 flex justify-between items-center">
              <h3 className="text-xl font-black text-slate-900 flex items-center gap-3">
                <span className="material-symbols-outlined text-[#ee2b2b]">history</span>
                Donation History & Performance
              </h3>
              <span className="text-xs font-bold text-slate-400">Total Tokens Earned: {(donor.history.reduce((a: any, b: any) => a + b.tokens, 0)).toLocaleString()}</span>
            </div>

            <div className="p-8">
              <div className="space-y-4">
                {donor.history.map((entry: any, i: number) => (
                  <motion.div
                    key={i}
                    initial={{ x: 20, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ delay: i * 0.1 }}
                    className="group flex flex-col sm:flex-row items-center justify-between p-6 rounded-2xl bg-slate-50 border border-slate-100 hover:border-[#ee2b2b]/30 transition-all"
                  >
                    <div className="flex items-center gap-6 mb-4 sm:mb-0">
                      <div className="w-12 h-12 bg-white rounded-xl shadow-sm flex flex-col items-center justify-center">
                        <span className="text-[10px] font-black text-slate-400 uppercase">{entry.date.split(' ')[0]}</span>
                        <span className="text-lg font-black text-slate-900">{entry.date.split(' ')[1].replace(',', '')}</span>
                      </div>
                      <div>
                        <p className="font-extrabold text-slate-900">{entry.location}</p>
                        <p className="text-xs font-bold text-slate-400 mt-0.5">{entry.date}</p>
                      </div>
                    </div>

                    <div className="flex items-center gap-12 w-full sm:w-auto justify-between sm:justify-start">
                      <div className="text-center sm:text-right">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Quantity</p>
                        <p className="font-black text-[#ee2b2b] text-lg">{entry.quantity}</p>
                      </div>
                      <div className="text-center sm:text-right">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Tokens Awarded</p>
                        <div className="flex items-center gap-1.5 sm:justify-end text-lg font-black text-amber-600">
                          <span className="material-symbols-outlined text-sm">toll</span>
                          {entry.tokens}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>

              <div className="mt-8 p-6 bg-amber-50 rounded-2xl border border-amber-100 flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-600">
                  <span className="material-symbols-outlined">emoji_events</span>
                </div>
                <div>
                  <p className="font-black text-amber-900 text-sm italic">"Loyalty Impact: This donor has saved approximately {(donor.totalDonations * 3)} lives through consistent contributions."</p>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-3xl border border-slate-200 p-8 shadow-sm">
            <h4 className="font-black text-slate-900 mb-6 uppercase tracking-widest text-xs">Medical Insight Trends</h4>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
              <div>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Avg Yield</p>
                <p className="font-black text-slate-900 mt-1">475ml</p>
              </div>
              <div>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Recovery</p>
                <p className="font-black text-emerald-600 mt-1">FAST</p>
              </div>
              <div>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Consistency</p>
                <p className="font-black text-slate-900 mt-1">98%</p>
              </div>
              <div>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Matches</p>
                <p className="font-black text-slate-900 mt-1">4 Urgent</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Verification Modal */}
      {isVerifying && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[200] flex items-center justify-center p-6 animate-in fade-in duration-300">
          <motion.div
            initial={{ scale: 0.9, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            className="bg-white w-full max-w-2xl rounded-[2.5rem] overflow-hidden shadow-2xl"
          >
            <div className="p-8 bg-slate-900 text-white flex justify-between items-center">
              <div className="flex items-center gap-3">
                <span className="material-symbols-outlined text-[#ee2b2b]">verified_user</span>
                <div>
                  <h4 className="font-black text-lg">Document Verification</h4>
                  <p className="text-[10px] text-white/50 font-bold uppercase tracking-widest">Checking: {donor.name}</p>
                </div>
              </div>
              <button
                onClick={() => setIsVerifying(false)}
                className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-all"
              >
                <span className="material-symbols-outlined text-sm">close</span>
              </button>
            </div>

            <div className="p-10 space-y-8">
              <div className="grid grid-cols-2 gap-6">
                <div className="space-y-3">
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">National Identity (scanned)</p>
                  <div className="aspect-[4/3] rounded-2xl bg-slate-100 border-2 border-dashed border-slate-200 flex flex-col items-center justify-center text-slate-400 group hover:border-[#ee2b2b]/30 transition-all cursor-pointer">
                    <span className="material-symbols-outlined text-4xl mb-2">badge</span>
                    <span className="text-[10px] font-bold">CLICK TO ENLARGE ID</span>
                  </div>
                </div>
                <div className="space-y-3">
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Medical Clearance</p>
                  <div className="aspect-[4/3] rounded-2xl bg-slate-100 border-2 border-dashed border-slate-200 flex flex-col items-center justify-center text-slate-400 group hover:border-[#ee2b2b]/30 transition-all cursor-pointer">
                    <span className="material-symbols-outlined text-4xl mb-2">description</span>
                    <span className="text-[10px] font-bold">VIEW MEDICAL RECORDS</span>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <div className="flex items-start gap-4 p-4 bg-emerald-50 rounded-2xl border border-emerald-100">
                  <span className="material-symbols-outlined text-emerald-600 mt-1">check_circle</span>
                  <div>
                    <p className="text-sm font-black text-emerald-900">AI Pre-Scan Passed</p>
                    <p className="text-[11px] text-emerald-700 mt-1 font-medium">Auto-analysis detected valid document signatures and matching biometric identifiers.</p>
                  </div>
                </div>

                <div className="flex items-start gap-4 p-4 bg-slate-50 rounded-2xl border border-slate-100">
                  <span className="material-symbols-outlined text-slate-400 mt-1">info</span>
                  <div className="text-[11px] text-slate-500 leading-relaxed">
                    By confirming verification, you agree that you have manually cross-checked the scanned documents against the donor's digital profile.
                  </div>
                </div>
              </div>

              <div className="flex gap-4">
                <button
                  onClick={() => setIsVerifying(false)}
                  className="flex-1 py-5 bg-slate-100 text-slate-400 font-black rounded-2xl hover:bg-slate-200 hover:text-slate-600 transition-all"
                >
                  Reject & Flags
                </button>
                <button
                  onClick={handleVerify}
                  className="flex-[2] py-5 bg-[#ee2b2b] text-white rounded-2xl font-black shadow-xl shadow-[#ee2b2b]/20 hover:scale-[1.02] transition-all flex items-center justify-center gap-3"
                >
                  <span className="material-symbols-outlined">verified</span>
                  Approve Verification
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}

function KPICard({ title, value, icon, color, trend, progress }: any) {
  const colorClasses: any = {
    red: "bg-[#ee2b2b]/10 text-[#ee2b2b]",
    blue: "bg-blue-100 text-blue-600",
    amber: "bg-amber-100 text-amber-600"
  };
  const barColors: any = {
    red: "bg-[#ee2b2b]",
    blue: "bg-blue-500",
    amber: "bg-amber-500"
  };

  return (
    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
      <div className="flex justify-between items-start mb-4">
        <div className={`p-2 rounded-lg ${colorClasses[color]}`}>
          <span className="material-symbols-outlined">{icon}</span>
        </div>
        <span className="flex items-center text-emerald-500 text-sm font-bold">
          <span className="material-symbols-outlined text-sm mr-1">trending_up</span>
          {trend}
        </span>
      </div>
      <h3 className="text-slate-500 text-sm font-medium">{title}</h3>
      <p className="text-3xl font-extrabold text-slate-900 mt-1">{value}</p>
      <div className="mt-4 w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
        <div className={`${barColors[color]} h-full rounded-full`} style={{ width: `${progress}%` }}></div>
      </div>
    </div>
  );
}

function FeedbackItem({ name, initial, rating, text, role, time, color }: any) {
  return (
    <div className="p-4 rounded-lg bg-slate-50 border border-slate-100 transition-all hover:border-[#ee2b2b]/30">
      <div className="flex justify-between items-start mb-2">
        <div className="flex items-center gap-2">
          <div className={`w-6 h-6 rounded flex items-center justify-center text-[10px] font-bold ${color === 'red' ? 'bg-[#ee2b2b]/20 text-[#ee2b2b]' : 'bg-slate-200'}`}>
            {initial}
          </div>
          <span className="text-xs font-bold">{name}</span>
        </div>
        <div className="flex text-amber-400">
          {[...Array(5)].map((_, i) => (
            <span key={i} className={`material-symbols-outlined text-xs ${i >= rating ? 'text-slate-300' : ''}`}>star</span>
          ))}
        </div>
      </div>
      <p className="text-sm text-slate-600 leading-relaxed italic">"{text}"</p>
      <div className="mt-3 flex justify-between items-center text-[10px] text-slate-400 font-medium">
        <span>{role}</span>
        <span>{time}</span>
      </div>
    </div>
  );
}
